plugins {
    id 'java'
    id "org.sonarqube" version "7.1.0.6387"
    id"co.uzzu.dotenv.gradle" version "4.0.0"
}

group = 'org'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.15.2'
}

test {
    useJUnitPlatform()
}

sonar {
    properties {
        property "sonar.projectKey", "ShopSimulator"
        property "sonar.projectName", "ShopSimulator"
        property "sonar.host.url", "http://localhost:9000"
        property "sonar.token", ""
    }
}

